services:
  # ──────────────────────────────────────────────
  #  Frontend Nginx
  # ──────────────────────────────────────────────
  - type: web
    name: spacevenue-frontend
    env: docker
    dockerfile: ./frontend/Dockerfile
    region: ohio
    plan: free
    ports:
      - key: 80

  # ──────────────────────────────────────────────
  #  Backend Spring Boot
  # ──────────────────────────────────────────────
  - type: pserv
    name: spacevenue-backend
    env: docker
    dockerfile: ./Dockerfile
    region: ohio
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - fromGroup: spacevenue-secrets
