services:
  # ──────────────────────────────────────────────
  #  Frontend Nginx
  # ──────────────────────────────────────────────
  - type: web
    name: spacevenue-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    region: ohio
    plan: free

  # ──────────────────────────────────────────────
  #  Backend Spring Boot
  # ──────────────────────────────────────────────
  - type: web
    name: spacevenue-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: ohio
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - fromGroup: spacevenue-secrets

# ──────────────────────────────────────────────
#  Grupo de Variables de Entorno
# ──────────────────────────────────────────────
envVarGroups:
  - name: spacevenue-secrets
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: GOOGLE_OAUTH2_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH2_CLIENT_SECRET
        sync: false
      - key: GOOGLE_OAUTH2_REDIRECT_URI
        sync: false
      - key: GOOGLE_CREDENTIALS_BASE64
        sync: false
      - key: ID_FOR_GOOGLE_CALENDAR
        sync: false
